ALTER TABLE "clubs"
ADD COLUMN "reminder_day" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN "overdue_day" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "reminder_hour" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "reminder_tz" TEXT NOT NULL DEFAULT 'Europe/Sofia';
