-- This migration is intentionally a no-op.
-- The next migration (`20260314120000_replace_schema_with_clubs_players_payment_logs`)
-- drops and recreates the relevant tables, so executing SQL here is unnecessary
-- and breaks shadow database replay due to historical schema inconsistencies.
